export const actions = {
  FETCH_GITHUB_USERS: 'FETCH_GITHUB_USERS',
  FETCH_GITHUB_USERS_SUCCESS: 'FETCH_GITHUB_USERS_SUCCESS',
  FETCH_GITHUB_USERS_FAILURE: 'FETCH_GITHUB_USERS_FAILURE',
  FETCH_MORE_BEGIN: 'FETCH_MORE_BEGIN',
  FETCH_MORE_END: 'FETCH_MORE_END',
  RESET_STATE: 'RESET_STATE',
}

export const GITHUB_API:string = 'https://api.github.com/search/users';